name: Sync workflow

on:
  schedule:
    - cron: '0/15 * * * *' 


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git remote add upstream $GITHUB_SERVER_URL/${{ secrets.PARENT_REPO }}/${{ github.repository.name }}
          git fetch upstream
          git checkout master
          git merge  upstream/master
          git push
